### ISSUE TITLE
Support for PATHS query

### ISSUE THREAD

**Issue by petrsimon** [stardog-union/stardog.js#117]
Hi,
Are you planning to support this type of query soon? It works fine in Clojure and using commandline `stardog` client, but in Javascript it throws
```
TypeError: Cannot read property 'toString' of null
    at /home/petr/dev/tbdb/fena-webpack/node_modules/node-fetch/lib/headers.js:40:27
    at Array.forEach (native)
    at new Headers (/home/petr/dev/tbdb/fena-webpack/node_modules/node-fetch/lib/headers.js:39:18)
    at Body.Request (/home/petr/dev/tbdb/fena-webpack/node_modules/node-fetch/lib/request.js:40:17)
    at /home/petr/dev/tbdb/fena-webpack/node_modules/node-fetch/index.js:51:17
    at new Fetch (/home/petr/dev/tbdb/fena-webpack/node_modules/node-fetch/index.js:49:9)
    at Fetch (/home/petr/dev/tbdb/fena-webpack/node_modules/node-fetch/index.js:37:10)
    at /home/petr/dev/tbdb/fena-webpack/node_modules/fetch-ponyfill/fetch-node.js:15:12
    at dispatchQuery (/home/petr/dev/tbdb/fena-webpack/node_modules/stardog/lib/query/main.js:15:10)
```

I've naively added the `paths` type into `utils.js` to return `'application/sparql-results+json'`, but the results don't seem right and some paths are not found.
Thanks!

**Comment by snowell** [comment]
Hi,

Yes, we will have this functionality in the next release, which should be fairly soon

**Comment by petrsimon** [comment]
Lovely, thanks a lot.
